/*
 * Vulkan Common Runtime Stubs
 * 
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: scripts/generate-vk-common-stubs.py
 * 
 * Stubs for vk_common_* functions that are referenced
 * in KosmicKrisp entrypoints but not implemented (optional extensions).
 */

#include <vulkan/vulkan.h>

VKAPI_ATTR VkResult VKAPI_CALL vk_common_AcquireDrmDisplayEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_AcquireFullScreenExclusiveModeEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_AcquireImageANDROID(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_AcquireImageOHOS(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_AcquireNextImage2KHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_AcquireNextImageKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_AcquirePerformanceConfigurationINTEL(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_AcquireProfilingLockKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_AcquireWinrtDisplayNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_AcquireXlibDisplayEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_AllocateDescriptorSets(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_AllocateMemory(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_AntiLagUpdateAMD(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_BeginCommandBuffer(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_BindAccelerationStructureMemoryNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_BindBufferMemory2(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_BindBufferMemory2KHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_BindDataGraphPipelineSessionMemoryARM(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_BindImageMemory2(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_BindImageMemory2KHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_BindOpticalFlowSessionImageNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_BindTensorMemoryARM(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_BindVideoSessionMemoryKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_BuildAccelerationStructuresKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_BuildMicromapsEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBeginConditionalRenderingEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBeginCustomResolveEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBeginPerTileExecutionQCOM(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBeginQueryIndexedEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBeginRenderPass2KHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBeginRendering(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBeginRenderingKHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBeginTransformFeedbackEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBeginVideoCodingKHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBindDescriptorBufferEmbeddedSamplers2EXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBindDescriptorBuffersEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBindDescriptorSets2(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBindDescriptorSets2KHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBindIndexBuffer2(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBindIndexBuffer2KHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBindInvocationMaskHUAWEI(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBindPipelineShaderGroupNV(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBindShadingRateImageNV(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBindTileMemoryQCOM(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBindTransformFeedbackBuffersEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBindVertexBuffers2(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBindVertexBuffers2EXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBlitImage2(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBlitImage2KHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBuildAccelerationStructureNV(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBuildAccelerationStructuresIndirectKHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBuildAccelerationStructuresKHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBuildClusterAccelerationStructureIndirectNV(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBuildMicromapsEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdBuildPartitionedAccelerationStructuresNV(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdClearAttachments(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdClearColorImage(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdClearDepthStencilImage(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdControlVideoCodingKHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdConvertCooperativeVectorMatrixNV(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdCopyAccelerationStructureKHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdCopyAccelerationStructureNV(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdCopyAccelerationStructureToMemoryKHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdCopyBuffer2(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdCopyBuffer2KHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdCopyBufferToImage2(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdCopyBufferToImage2KHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdCopyImage2(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdCopyImage2KHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdCopyImageToBuffer2(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdCopyImageToBuffer2KHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdCopyMemoryIndirectKHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdCopyMemoryIndirectNV(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdCopyMemoryToAccelerationStructureKHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdCopyMemoryToImageIndirectKHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdCopyMemoryToImageIndirectNV(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdCopyMemoryToMicromapEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdCopyMicromapEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdCopyMicromapToMemoryEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdCopyQueryPoolResults(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdCopyTensorARM(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdCuLaunchKernelNVX(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdCudaLaunchKernelNV(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDebugMarkerBeginEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDebugMarkerEndEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDebugMarkerInsertEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDecodeVideoKHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDecompressMemoryEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDecompressMemoryIndirectCountEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDecompressMemoryIndirectCountNV(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDecompressMemoryNV(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDispatchBase(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDispatchBaseKHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDispatchDataGraphARM(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDispatchGraphAMDX(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDispatchGraphIndirectAMDX(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDispatchGraphIndirectCountAMDX(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDispatchIndirect(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDispatchTileQCOM(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDraw(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDrawClusterHUAWEI(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDrawClusterIndirectHUAWEI(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDrawIndexed(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDrawIndexedIndirect(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDrawIndexedIndirectCount(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDrawIndexedIndirectCountAMD(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDrawIndexedIndirectCountKHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDrawIndirect(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDrawIndirectByteCountEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDrawIndirectCount(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDrawIndirectCountAMD(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDrawIndirectCountKHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDrawMeshTasksEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDrawMeshTasksIndirectCountEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDrawMeshTasksIndirectCountNV(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDrawMeshTasksIndirectEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDrawMeshTasksIndirectNV(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDrawMeshTasksNV(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDrawMultiEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdDrawMultiIndexedEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdEncodeVideoKHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdEndConditionalRenderingEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdEndPerTileExecutionQCOM(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdEndQueryIndexedEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdEndRenderPass2KHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdEndRendering2EXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdEndRendering2KHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdEndRenderingKHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdEndTransformFeedbackEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdEndVideoCodingKHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdExecuteGeneratedCommandsEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdExecuteGeneratedCommandsNV(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdFillBuffer(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdInitializeGraphScratchMemoryAMDX(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdNextSubpass2KHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdOpticalFlowExecuteNV(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdPipelineBarrier2(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdPipelineBarrier2KHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdPreprocessGeneratedCommandsEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdPreprocessGeneratedCommandsNV(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdPushConstants2(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdPushConstants2KHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdPushDescriptorSet(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdPushDescriptorSet2(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdPushDescriptorSet2KHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdPushDescriptorSetWithTemplate(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdPushDescriptorSetWithTemplate2(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdPushDescriptorSetWithTemplate2KHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdResetEvent2(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdResetEvent2KHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdResetQueryPool(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdResolveImage2(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdResolveImage2KHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetCheckpointNV(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetCoarseSampleOrderNV(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetCullModeEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetDepthBiasEnableEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetDepthBoundsTestEnableEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetDepthCompareOpEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetDepthTestEnableEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetDepthWriteEnableEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetDescriptorBufferOffsets2EXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetDeviceMaskKHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetEvent2(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetEvent2KHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetExclusiveScissorEnableNV(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetExclusiveScissorNV(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetFragmentShadingRateEnumNV(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetFrontFaceEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetLineStipple(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetLineStippleEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetPerformanceMarkerINTEL(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetPerformanceOverrideINTEL(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetPerformanceStreamMarkerINTEL(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetPrimitiveRestartEnableEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetPrimitiveTopologyEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetRasterizerDiscardEnableEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetRenderingAttachmentLocations(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetRenderingInputAttachmentIndices(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetScissorWithCountEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetStencilOpEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetStencilTestEnableEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetViewportShadingRatePaletteNV(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetViewportWScalingNV(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSetViewportWithCountEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdSubpassShadingHUAWEI(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdTraceRaysIndirect2KHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdTraceRaysIndirectKHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdTraceRaysKHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdTraceRaysNV(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdUpdateBuffer(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdUpdatePipelineIndirectBufferNV(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdWaitEvents2(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdWaitEvents2KHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdWriteAccelerationStructuresPropertiesKHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdWriteAccelerationStructuresPropertiesNV(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdWriteBufferMarker2AMD(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdWriteMicromapsPropertiesEXT(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdWriteTimestamp2(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR void VKAPI_CALL vk_common_CmdWriteTimestamp2KHR(void* dummy, ...) {
    (void)dummy;
    // Stub for optional extension
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CompileDeferredNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_ConvertCooperativeVectorMatrixNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CopyAccelerationStructureKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CopyAccelerationStructureToMemoryKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CopyImageToImage(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CopyImageToImageEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CopyImageToMemory(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CopyImageToMemoryEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CopyMemoryToAccelerationStructureKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CopyMemoryToImage(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CopyMemoryToImageEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CopyMemoryToMicromapEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CopyMicromapEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CopyMicromapToMemoryEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateAccelerationStructureKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateAccelerationStructureNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateAndroidSurfaceKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateBuffer(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateBufferCollectionFUCHSIA(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateBufferView(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateCuFunctionNVX(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateCuModuleNVX(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateCudaFunctionNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateCudaModuleNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateDataGraphPipelineSessionARM(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateDataGraphPipelinesARM(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateDescriptorPool(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateDescriptorSetLayout(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateDescriptorUpdateTemplateKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateDevice(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateDirectFBSurfaceEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateDisplayModeKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateDisplayPlaneSurfaceKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateEvent(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateExecutionGraphPipelinesAMDX(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateExternalComputeQueueNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateHeadlessSurfaceEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateIOSSurfaceMVK(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateImage(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateImagePipeSurfaceFUCHSIA(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateImageView(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateIndirectCommandsLayoutEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateIndirectCommandsLayoutNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateIndirectExecutionSetEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateInstance(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateMacOSSurfaceMVK(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateMetalSurfaceEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateMicromapEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateOpticalFlowSessionNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreatePrivateDataSlotEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateQueryPool(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateRayTracingPipelinesNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateRenderPass2KHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateSampler(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateSamplerYcbcrConversionKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateScreenSurfaceQNX(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateSharedSwapchainsKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateStreamDescriptorSurfaceGGP(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateSurfaceOHOS(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateSwapchainKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateTensorARM(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateTensorViewARM(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateValidationCacheEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateViSurfaceNN(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateVideoSessionKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateWaylandSurfaceKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateWin32SurfaceKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateXcbSurfaceKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_CreateXlibSurfaceKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DebugMarkerSetObjectTagEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyAccelerationStructureKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyAccelerationStructureNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyBuffer(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyBufferCollectionFUCHSIA(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyBufferView(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyCuFunctionNVX(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyCuModuleNVX(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyCudaFunctionNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyCudaModuleNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyDataGraphPipelineSessionARM(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyDescriptorPool(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyDescriptorUpdateTemplateKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyDevice(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyEvent(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyExternalComputeQueueNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyImage(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyImageView(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyIndirectCommandsLayoutEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyIndirectCommandsLayoutNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyIndirectExecutionSetEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyInstance(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyMicromapEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyOpticalFlowSessionNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyPrivateDataSlotEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyQueryPool(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroySampler(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroySamplerYcbcrConversionKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroySurfaceKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroySwapchainKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyTensorARM(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyTensorViewARM(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyValidationCacheEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DestroyVideoSessionKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_DisplayPowerControlEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_EndCommandBuffer(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_EnumerateInstanceExtensionProperties(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_EnumerateInstanceLayerProperties(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_EnumerateInstanceVersion(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_EnumeratePhysicalDeviceGroupsKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_EnumeratePhysicalDeviceQueueFamilyPerformanceCountersByRegionARM(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_EnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_ExportMetalObjectsEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_FlushMappedMemoryRanges(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_FreeDescriptorSets(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_FreeMemory(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetAccelerationStructureBuildSizesKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetAccelerationStructureDeviceAddressKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetAccelerationStructureHandleNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetAccelerationStructureMemoryRequirementsNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetAndroidHardwareBufferPropertiesANDROID(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetBufferCollectionPropertiesFUCHSIA(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetBufferDeviceAddressEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetBufferDeviceAddressKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetBufferMemoryRequirements2KHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetBufferOpaqueCaptureAddress(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetBufferOpaqueCaptureAddressKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetCalibratedTimestampsEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetClusterAccelerationStructureBuildSizesNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetCudaModuleCacheNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDataGraphPipelineAvailablePropertiesARM(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDataGraphPipelinePropertiesARM(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDataGraphPipelineSessionBindPointRequirementsARM(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDataGraphPipelineSessionMemoryRequirementsARM(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDescriptorEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDescriptorSetHostMappingVALVE(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDescriptorSetLayoutBindingOffsetEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDescriptorSetLayoutHostMappingInfoVALVE(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDescriptorSetLayoutSizeEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDescriptorSetLayoutSupport(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDescriptorSetLayoutSupportKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDeviceAccelerationStructureCompatibilityKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDeviceBufferMemoryRequirements(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDeviceBufferMemoryRequirementsKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDeviceFaultInfoEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDeviceGroupPeerMemoryFeaturesKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDeviceGroupPresentCapabilitiesKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDeviceGroupSurfacePresentModes2EXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDeviceGroupSurfacePresentModesKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDeviceImageMemoryRequirements(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDeviceImageMemoryRequirementsKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDeviceImageSparseMemoryRequirements(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDeviceImageSparseMemoryRequirementsKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDeviceImageSubresourceLayout(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDeviceImageSubresourceLayoutKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDeviceMemoryCommitment(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDeviceMemoryOpaqueCaptureAddress(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDeviceMemoryOpaqueCaptureAddressKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDeviceMicromapCompatibilityEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDeviceSubpassShadingMaxWorkgroupSizeHUAWEI(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDeviceTensorMemoryRequirementsARM(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDisplayModeProperties2KHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDisplayModePropertiesKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDisplayPlaneCapabilities2KHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDisplayPlaneCapabilitiesKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDisplayPlaneSupportedDisplaysKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDrmDisplayEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetDynamicRenderingTilePropertiesQCOM(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetEncodedVideoSessionParametersKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetEventStatus(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetExecutionGraphPipelineNodeIndexAMDX(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetExecutionGraphPipelineScratchSizeAMDX(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetExternalComputeQueueDataNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetFenceWin32HandleKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetFramebufferTilePropertiesQCOM(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetGeneratedCommandsMemoryRequirementsEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetGeneratedCommandsMemoryRequirementsNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetImageDrmFormatModifierPropertiesEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetImageMemoryRequirements2(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetImageMemoryRequirements2KHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetImageSparseMemoryRequirements2(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetImageSparseMemoryRequirements2KHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetImageSubresourceLayout2(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetImageSubresourceLayout2EXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetImageSubresourceLayout2KHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetImageViewAddressNVX(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetImageViewHandle64NVX(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetImageViewHandleNVX(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetInstanceProcAddr(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetLatencyTimingsNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetMemoryAndroidHardwareBufferANDROID(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetMemoryFdKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetMemoryFdPropertiesKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetMemoryHostPointerPropertiesEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetMemoryMetalHandleEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetMemoryMetalHandlePropertiesEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetMemoryNativeBufferOHOS(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetMemoryRemoteAddressNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetMemoryWin32HandleKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetMemoryWin32HandleNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetMemoryWin32HandlePropertiesKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetMemoryZirconHandleFUCHSIA(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetMemoryZirconHandlePropertiesFUCHSIA(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetMicromapBuildSizesEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetNativeBufferPropertiesOHOS(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPartitionedAccelerationStructuresBuildSizesNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPastPresentationTimingGOOGLE(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPerformanceParameterINTEL(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceCalibrateableTimeDomainsEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceCooperativeMatrixFlexibleDimensionsPropertiesNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceCooperativeMatrixPropertiesKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceCooperativeMatrixPropertiesNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceCooperativeVectorPropertiesNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceDirectFBPresentationSupportEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceDisplayPlaneProperties2KHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceDisplayPlanePropertiesKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceDisplayProperties2KHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceDisplayPropertiesKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceExternalBufferProperties(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceExternalBufferPropertiesKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceExternalFencePropertiesKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceExternalImageFormatPropertiesNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceExternalSemaphorePropertiesKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceExternalTensorPropertiesARM(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceFeatures2KHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceFormatProperties2(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceFormatProperties2KHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceFragmentShadingRatesKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceImageFormatProperties2(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceImageFormatProperties2KHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceMemoryProperties2(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceMemoryProperties2KHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceMultisamplePropertiesEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceOpticalFlowImageFormatsNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDevicePresentRectanglesKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceProperties2KHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceQueueFamilyDataGraphProcessingEnginePropertiesARM(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceQueueFamilyDataGraphPropertiesARM(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceQueueFamilyProperties2(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceQueueFamilyProperties2KHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceScreenPresentationSupportQNX(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceSparseImageFormatProperties2(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceSparseImageFormatProperties2KHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceSurfaceCapabilities2EXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceSurfaceCapabilities2KHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceSurfaceCapabilitiesKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceSurfaceFormats2KHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceSurfaceFormatsKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceSurfacePresentModes2EXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceSurfacePresentModesKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceSurfaceSupportKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceToolPropertiesEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceVideoCapabilitiesKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceVideoEncodeQualityLevelPropertiesKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceVideoFormatPropertiesKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceWaylandPresentationSupportKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceWin32PresentationSupportKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceXcbPresentationSupportKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPhysicalDeviceXlibPresentationSupportKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPipelineIndirectDeviceAddressNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPipelineIndirectMemoryRequirementsNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPipelinePropertiesEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetPrivateDataEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetQueryPoolResults(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetQueueCheckpointData2NV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetRandROutputDisplayEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetRayTracingShaderGroupHandlesNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetRefreshCycleDurationGOOGLE(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetRenderingAreaGranularity(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetScreenBufferPropertiesQNX(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetSemaphoreCounterValueKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetSemaphoreWin32HandleKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetSemaphoreZirconHandleFUCHSIA(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetShaderInfoAMD(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetSwapchainCounterEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetSwapchainGrallocUsage2ANDROID(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetSwapchainGrallocUsageANDROID(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetSwapchainGrallocUsageOHOS(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetSwapchainImagesKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetSwapchainStatusKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetTensorMemoryRequirementsARM(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetTensorOpaqueCaptureDescriptorDataARM(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetTensorViewOpaqueCaptureDescriptorDataARM(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetValidationCacheDataEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetVideoSessionMemoryRequirementsKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_GetWinrtDisplayNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_ImportFenceWin32HandleKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_ImportSemaphoreWin32HandleKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_ImportSemaphoreZirconHandleFUCHSIA(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_InitializePerformanceApiINTEL(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_InvalidateMappedMemoryRanges(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_LatencySleepNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_MapMemory2(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_MapMemory2KHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_MergeValidationCachesEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_QueueNotifyOutOfBandNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_QueuePresentKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_QueueSetPerformanceConfigurationINTEL(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_QueueSignalReleaseImageANDROID(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_QueueSignalReleaseImageOHOS(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_QueueSubmit2KHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_RegisterDeviceEventEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_RegisterDisplayEventEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_ReleaseDisplayEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_ReleaseFullScreenExclusiveModeEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_ReleasePerformanceConfigurationINTEL(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_ReleaseProfilingLockKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_ReleaseSwapchainImagesEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_ReleaseSwapchainImagesKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_ResetDescriptorPool(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_ResetEvent(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_ResetQueryPool(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_ResetQueryPoolEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_SetBufferCollectionBufferConstraintsFUCHSIA(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_SetBufferCollectionImageConstraintsFUCHSIA(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_SetDeviceMemoryPriorityEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_SetEvent(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_SetHdrMetadataEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_SetLatencyMarkerNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_SetLatencySleepModeNV(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_SetLocalDimmingAMD(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_SetPrivateDataEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_SignalSemaphoreKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_TransitionImageLayout(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_TransitionImageLayoutEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_TrimCommandPoolKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_UninitializePerformanceApiINTEL(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_UnmapMemory2(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_UnmapMemory2KHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_UpdateDescriptorSetWithTemplate(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_UpdateDescriptorSetWithTemplateKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_UpdateDescriptorSets(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_UpdateIndirectExecutionSetPipelineEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_UpdateIndirectExecutionSetShaderEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_WaitForPresent2KHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_WaitForPresentKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_WaitSemaphoresKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_WriteAccelerationStructuresPropertiesKHR(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}

VKAPI_ATTR VkResult VKAPI_CALL vk_common_WriteMicromapsPropertiesEXT(void* dummy, ...) {
    (void)dummy;
    return VK_ERROR_EXTENSION_NOT_PRESENT;
}
