# Makefile for test client
CC = clang
CFLAGS = -Wall -Wextra -std=c11
LDFLAGS = -lwayland-client

WAYLAND_INC = /opt/homebrew/include
WAYLAND_LIB = /opt/homebrew/lib

macos_wlclient_test: test_client.c test_xdg-shell-client-protocol.h test_xdg-shell-client-protocol.c src/logging.c
	$(CC) $(CFLAGS) -Isrc -I$(WAYLAND_INC) -L$(WAYLAND_LIB) -o macos_wlclient_test test_client.c test_xdg-shell-client-protocol.c src/logging.c $(LDFLAGS)

macos_wlclient_color_test: test_color_client.c test_xdg-shell-client-protocol.h test_xdg-shell-client-protocol.c test_color-management-v1-client-protocol.h test_color-management-v1-client-protocol.c src/logging.c
	$(CC) $(CFLAGS) -Isrc -I$(WAYLAND_INC) -L$(WAYLAND_LIB) -o macos_wlclient_color_test test_color_client.c test_xdg-shell-client-protocol.c test_color-management-v1-client-protocol.c src/logging.c $(LDFLAGS) -lm

macos_wlclient_input_test: test_input_client.c test_xdg-shell-client-protocol.h test_xdg-shell-client-protocol.c src/logging.c
	$(CC) $(CFLAGS) -Isrc -I$(WAYLAND_INC) -L$(WAYLAND_LIB) -o macos_wlclient_input_test test_input_client.c test_xdg-shell-client-protocol.c src/logging.c $(LDFLAGS)

clean:
	rm -f macos_wlclient_test macos_wlclient_input_test macos_wlclient_color_test

.PHONY: clean

