# Wawona Test Suite Makefile
# Run: make -f Makefile.test test

.PHONY: test test-protocols test-functionality test-all clean-tests

BUILD_DIR ?= build
TESTS_DIR = tests

test: test-all

test-protocols:
	@echo "=== Running Protocol Compliance Tests ==="
	@cd $(TESTS_DIR) && $(MAKE) test

test-functionality:
	@echo "=== Running Functionality Tests ==="
	@$(TESTS_DIR)/test_protocol_functionality.sh

test-all: test-protocols test-functionality
	@echo ""
	@echo "=== All Tests Complete ==="

clean-tests:
	@cd $(TESTS_DIR) && $(MAKE) clean

